"""Top-level package for the Slay the Spire RL research stack."""

from .agents import BaselinePolicy, HeuristicPolicy, RandomPolicy, legal_actions
from .bootstrap import ProjectInfo, get_project_info
from .env import (
    ACTION_ORDER,
    OBSERVATION_FIELDS,
    Action,
    CombatantState,
    CombatEnvironment,
    CombatState,
    CombatTrainingEnv,
    DrawResult,
    EncounterConfig,
    InvalidActionError,
    PileState,
    StepResult,
    action_to_index,
    create_initial_combat_state,
    decode_action_index,
    draw_cards,
    encode_action_mask,
    encode_observation,
    enemy_intent_damage,
    legal_action_mask,
)
from .evaluation import (
    EpisodeMetrics,
    EvaluationSummary,
    evaluate_episode,
    evaluate_heuristic_policy,
    evaluate_policy,
    evaluate_random_policy,
)

__all__ = [
    "Action",
    "ACTION_ORDER",
    "BaselinePolicy",
    "CombatState",
    "CombatantState",
    "CombatEnvironment",
    "CombatTrainingEnv",
    "DrawResult",
    "EncounterConfig",
    "EpisodeMetrics",
    "EvaluationSummary",
    "HeuristicPolicy",
    "InvalidActionError",
    "OBSERVATION_FIELDS",
    "PileState",
    "ProjectInfo",
    "RandomPolicy",
    "StepResult",
    "action_to_index",
    "create_initial_combat_state",
    "decode_action_index",
    "draw_cards",
    "enemy_intent_damage",
    "encode_action_mask",
    "encode_observation",
    "evaluate_episode",
    "evaluate_heuristic_policy",
    "evaluate_policy",
    "evaluate_random_policy",
    "get_project_info",
    "legal_action_mask",
    "legal_actions",
]
__version__ = "0.1.0"
