"""Top-level package for the Slay the Spire RL research stack."""

from .bootstrap import ProjectInfo, get_project_info
from .env import (
    CARD_LIBRARY,
    CardDefinition,
    CardState,
    CombatAction,
    CombatEnvironment,
    CombatState,
    DrawResult,
    EncounterConfig,
    EndTurnAction,
    InvalidActionError,
    MonsterConfig,
    MonsterIntent,
    MonsterState,
    PileState,
    PlayCardAction,
    PlayerState,
    StepResult,
    apply_action,
    create_initial_combat_state,
    draw_cards,
    legal_actions,
)

__all__ = [
    "CARD_LIBRARY",
    "CardDefinition",
    "CardState",
    "CombatAction",
    "CombatState",
    "CombatEnvironment",
    "DrawResult",
    "EndTurnAction",
    "EncounterConfig",
    "InvalidActionError",
    "MonsterConfig",
    "MonsterIntent",
    "MonsterState",
    "PileState",
    "PlayCardAction",
    "PlayerState",
    "ProjectInfo",
    "StepResult",
    "apply_action",
    "create_initial_combat_state",
    "draw_cards",
    "get_project_info",
    "legal_actions",
]
__version__ = "0.1.0"
